"""C# worker/UI checks shared by production and Pages verification."""
from playwright.sync_api import expect
from pathlib import Path
import json


def verify_csharp_analysis(browser, base_url):
    context = browser.new_context()
    page = context.new_page()
    paths = []
    context.on('request', lambda request: paths.append(request.url))
    page.goto(base_url + '/', wait_until='networkidle')
    page.get_by_role('button', name='Import source…').first.click()
    dialog = page.locator('dialog')
    language = dialog.get_by_label('Language', exact=False)
    language.select_option('csharp')
    project_ids = "Object.keys(localStorage).filter(k => k.startsWith('vvs_project_')).map(k => JSON.parse(localStorage.getItem(k))).filter(p => p && typeof p.projectId === 'string').map(p => p.projectId).sort()"
    before_projects = page.evaluate(project_ids)
    source = '#nullable enable\n// 🧭 retained\nnamespace Samples { public static class Café { public static int Add(byte a, byte b) => a + b; public static string? Choose(bool flag, string? text) => flag ? text : null; } }\n'
    dialog.get_by_label('Original source').fill(source)
    # Hold the cold grammar request, so cancellation/deadline checks are deterministic.
    for mode in ['cancel', 'deadline']:
        held = []
        pattern = '**/source-parsers/tree-sitter-c_sharp.wasm'
        page.route(pattern, lambda route: held.append(route))
        with page.expect_request(pattern):
            dialog.get_by_role('button', name='Analyze source').click()
        if mode == 'cancel':
            dialog.get_by_role('button', name='Cancel import').click()
            expect(dialog.get_by_role('alert')).to_have_text('Import cancelled.')
        else:
            expect(dialog.get_by_role('alert')).to_have_text('IMPORT_TIME_BUDGET', timeout=30000)
        expect(dialog.get_by_label('Original source')).to_have_value(source)
        expect(dialog.get_by_role('region', name='C# source analysis')).not_to_be_visible()
        for route in held:
            route.abort()
        page.unroute(pattern)
    dialog.get_by_role('button', name='Analyze source').click()
    analysis = dialog.get_by_role('region', name='C# source analysis')
    expect(analysis).to_contain_text('Source syntax read.', timeout=30000)
    expect(analysis).to_contain_text('No graph mapping for this source.')
    analysis.locator('summary').filter(has_text='Source declarations').click()
    expect(analysis).to_contain_text('Café')
    expect(analysis).to_contain_text('Choose')
    analysis.locator('summary').filter(has_text='Retained original source').click()
    expect(analysis.locator('pre').last).to_have_text(source)
    for asset in ['web-tree-sitter.js', 'web-tree-sitter.wasm', 'tree-sitter-c_sharp.wasm']:
        assert base_url.rstrip('/') + '/source-parsers/' + asset in paths, asset
    expect(dialog.get_by_role('button', name='Build and validate preview')).not_to_be_visible()
    expect(dialog.get_by_role('button', name='Accept as new project')).not_to_be_visible()
    assert page.evaluate(project_ids) == before_projects, 'C# analysis created a project'
    # Invalid syntax and valid syntax with a native semantic error both retain source.
    for text, message in [('class Broken { void Test( {', 'could not be read completely'),
                          ('public class Overflow { public const byte Value = 256; }', 'Source syntax read.')]:
        dialog.get_by_label('Original source').fill(text)
        dialog.get_by_role('button', name='Analyze source').click()
        expect(analysis).to_contain_text(message, timeout=30000)
        expect(dialog.get_by_label('Original source')).to_have_value(text)
        expect(dialog.get_by_role('button', name='Accept as new project')).not_to_be_visible()
    # Binding checks are explicitly scoped, and failed source can be edited/repaired.
    cases = [
        ('public static class Sample { public static object Test() { const int seed = 254; byte observed = seed + 1; return observed; } }', 'observed: byte', None),
        ('public static class Sample { public static object Test() { int value = 1; { int value = 2; } var observed = value; return observed; } }', None, 'CSHARP_DECLARATION_SPACE'),
        ('public static class Sample { public static object Test() { const int seed = 2147483647; var observed = unchecked(seed + 1); return observed; } }', 'observed: int', None),
    ]
    for text, observation, error in cases:
        dialog.get_by_label('Original source').fill(text)
        dialog.get_by_role('button', name='Analyze source').click()
        expect(analysis).to_contain_text('Source syntax read.', timeout=30000)
        analysis.locator('summary').filter(has_text='Fixed-integral binding checks').click()
        if observation:
            expect(analysis).to_contain_text(observation)
            expect(analysis.get_by_role('alert')).not_to_be_visible()
        if error:
            expect(analysis.get_by_role('alert')).to_contain_text(error)
        expect(dialog.get_by_label('Original source')).to_have_value(text)
        expect(dialog.get_by_role('button', name='Accept as new project')).not_to_be_visible()
    # File choice, then language switching, must clear retired analysis and use the right grammar.
    dialog.locator('input[type=file]').set_input_files({'name': 'retained.cs', 'mimeType': 'text/plain', 'buffer': source.encode('utf-8')})
    expect(dialog.get_by_label('Original source')).to_have_value(source)
    expect(analysis).not_to_be_visible()
    dialog.get_by_role('button', name='Analyze source').click()
    expect(analysis).to_contain_text('Source syntax read.', timeout=30000)
    language.select_option('go')
    expect(analysis).not_to_be_visible()
    dialog.get_by_role('button', name='Use example', exact=True).click()
    dialog.get_by_role('button', name='Analyze source').click()
    expect(dialog.get_by_role('button', name='Mapping candidate', exact=False)).to_be_visible(timeout=30000)
    print('C# worker/UI: cold-load cancel/deadline/recovery, source retention, native binding facts, shadowing error/repair, invalid syntax, .cs upload and Go switch passed', flush=True)
    context.close()
    verify_csharp_signatures(browser, base_url)
    verify_csharp_import(browser, base_url)


def verify_csharp_import(browser, base_url):
    """Real source import and three-way reimport, through the deployed worker."""
    context = browser.new_context()
    page = context.new_page()
    page.goto(base_url + '/', wait_until='networkidle')
    page.get_by_role('button', name='Import source…').first.click()
    dialog = page.locator('dialog')
    dialog.get_by_label('Language', exact=False).select_option('csharp')
    fixture = json.loads((Path(__file__).resolve().parents[3] / 'packages/source-import/test/csharp-import-browser.fixture.json').read_text(encoding='utf-8'))
    source = fixture['source']
    dialog.locator('input[type=file]').set_input_files({'name': fixture['fileName'], 'mimeType': 'text/plain', 'buffer': source.encode('utf-8')})
    dialog.get_by_role('button', name='Analyze source').click()
    candidate = dialog.get_by_role('button', name='Mapping candidate', exact=False)
    expect(candidate).to_be_visible(timeout=30000)
    expect(dialog.get_by_role('region', name='C# source analysis')).to_contain_text('A graph mapping candidate is available')
    candidate.click()
    expect(dialog.get_by_label('Compilation unit')).to_have_value('library')
    dialog.get_by_role('button', name='Build and validate preview').click()
    accept = dialog.get_by_role('button', name='Accept as new project')
    expect(accept).to_be_enabled(timeout=30000)
    expect(dialog.locator('pre').last).to_contain_text('byte Identity(byte @Value)')
    expect(dialog.locator('pre').last).to_contain_text('return @Value;')
    accept.click()
    page.wait_for_url('**/editor?**', wait_until='networkidle')
    welcome = page.get_by_role('dialog').filter(has=page.locator('#graph-help-title'))
    expect(welcome).to_be_visible(timeout=30000)
    welcome.get_by_role('button', name='Close', exact=True).click()
    code = page.locator('.cm-content').first
    expect(code).to_contain_text('byte Identity(byte @Value)', timeout=30000)
    expect(code).to_contain_text('(-2147483648)')
    read_project = "Object.keys(localStorage).filter(k => k.startsWith('vvs_project_')).map(k => JSON.parse(localStorage.getItem(k))).find(p => p.targetLanguage === 'csharp')"
    snapshot = page.evaluate(read_project)
    assert snapshot and len(snapshot['functions']) == 12
    assert all(node['data']['properties'].get('sourceOrigin') for doc in snapshot['documents'].values() for node in doc['nodes'])
    project_id = snapshot['projectId']
    identity = next(fn for fn in snapshot['functions'] if fn['name'] == 'Identity')
    definition = next(node for node in snapshot['documents']['main-graph']['nodes'] if node['data']['properties'].get('nativeSignatureLanguage') == 'csharp' and node['data'].get('graphBinding', {}).get('symbolId') == identity['id'])
    page.get_by_role('button', name='View', exact=True).click()
    page.get_by_role('button', name='Zoom to fit all', exact=True).click()
    page.locator('.react-flow__node[data-id="' + definition['id'] + '"]').click()
    page.locator('summary').filter(has_text='Native signature').click()
    parameter = page.get_by_label('Native type for @Value', exact=True)
    result = page.get_by_label('Native return type', exact=True)
    parameter.select_option('int')
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).to_be_visible(timeout=30000)
    expect(page.get_by_role('button', name='Copy code', exact=True)).to_be_disabled()
    parameter.select_option('byte')
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).not_to_be_visible(timeout=30000)
    result.select_option('ushort')
    expect(code).to_contain_text('ushort Identity(byte @Value)', timeout=30000)
    page.keyboard.press('Control+s')
    page.wait_for_function("id => JSON.parse(localStorage.getItem('vvs_project_' + id)).documents['main-graph'].nodes.some(n => n.data.properties?.nativeReturnType === 'ushort')", arg=project_id)
    page.reload(wait_until='networkidle')
    expect(code).to_contain_text('ushort Identity(byte @Value)', timeout=30000)
    page.get_by_text('Function: Identity', exact=True).click()
    expect(code).to_contain_text('ushort Identity(byte @Value)', timeout=30000)
    expect(code).to_contain_text('return @Value;')

    def compare(text):
        page.get_by_role('button', name='File', exact=True).click()
        page.get_by_role('button', name='Re-import source…', exact=True).click()
        review = page.locator('dialog')
        review.get_by_label('Updated source', exact=True).fill(text)
        review.get_by_role('button', name='Compare source and graph').click()
        return review

    # Unchanged source keeps the inspector's graph-only widening by default.
    review = compare(source)
    expect(review.get_by_role('button', name='Apply reviewed re-import')).to_be_enabled(timeout=30000)
    review.get_by_role('button', name='Apply reviewed re-import').click()
    expect(review).not_to_be_visible()
    expect(code).to_contain_text('ushort Identity(byte @Value)', timeout=30000)
    replacement = source.replace('=> -2147483648', '=> -2147483647')
    review = compare(replacement)
    expect(review.get_by_label('Resolve this file')).to_be_visible(timeout=30000)
    expect(review.get_by_role('button', name='Apply reviewed re-import')).to_be_disabled()
    review.get_by_label('Resolve this file').select_option('keep-graph')
    review.get_by_role('button', name='Apply reviewed re-import').click()
    expect(review).not_to_be_visible()
    expect(code).to_contain_text('ushort Identity(byte @Value)', timeout=30000)
    review = compare(replacement)
    review.get_by_label('Resolve this file').select_option('use-source')
    review.get_by_role('button', name='Apply reviewed re-import').click()
    expect(review).not_to_be_visible()
    expect(code).to_contain_text('byte Identity(byte @Value)', timeout=30000)
    page.keyboard.press('Control+s')
    page.wait_for_function("id => JSON.parse(localStorage.getItem('vvs_project_' + id)).documents['main-graph'].nodes.some(n => n.data.properties?.sourceImport?.source.includes('-2147483647'))", arg=project_id)
    page.reload(wait_until='networkidle')
    page.get_by_text('Function: Minimum', exact=True).click()
    expect(code).to_contain_text('(-2147483647)', timeout=30000)
    saved = page.evaluate(read_project)
    assert saved['projectId'] == project_id and len(saved['functions']) == 12
    review = compare(replacement + '\nclass Additional {}')
    expect(review.get_by_role('alert')).to_be_visible(timeout=30000)
    expect(review.get_by_role('button', name='Apply reviewed re-import')).not_to_be_visible()
    review.get_by_role('button', name='Close', exact=True).click()
    expect(code).to_contain_text('(-2147483647)')
    page.get_by_text('Function: Done', exact=True).click()
    expect(code).to_contain_text('void Done(byte Value)', timeout=30000)
    expect(code).to_contain_text('int Third = (Value + Second);')
    assert 'return;' not in code.inner_text()
    done = next(fn for fn in saved['functions'] if fn['name'] == 'Done')
    assert not any(node['data'].get('kindId') == 'flow_return' for node in saved['documents'][done['id']]['nodes'])

    # Local source admission uses visible declaration types after function-tab reload.
    page.get_by_text('Function: Locals', exact=True).click()
    expect(code).to_contain_text('const byte @First = unchecked(((byte)256));', timeout=30000)
    expect(code).to_contain_text('var Second = @First;')
    expect(code).to_contain_text('byte Third = Second;')
    expect(code).to_contain_text('Third = 255;')
    local_function = next(fn for fn in saved['functions'] if fn['name'] == 'Locals')
    declaration = next(node for node in saved['documents'][local_function['id']]['nodes'] if node['data']['properties'].get('nativeLocalStyle') == 'csharp-const')
    page.get_by_role('button', name='View', exact=True).click()
    page.get_by_role('button', name='Zoom to fit all', exact=True).click()
    page.locator('.react-flow__node[data-id="' + declaration['id'] + '"]').click()
    native_type = page.get_by_label('Native scalar type', exact=True)
    native_type.click()
    assert page.get_by_role('option').all_text_contents() == ['sbyte', 'byte', 'short', 'ushort', 'int', 'uint', 'long', 'ulong', 'char']
    page.get_by_role('option', name='int', exact=True).click()
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).to_be_visible(timeout=30000)
    expect(page.get_by_role('button', name='Copy code', exact=True)).to_be_disabled()
    native_type.click()
    page.get_by_role('option', name='byte', exact=True).click()
    expect(code).to_contain_text('byte Third = Second;', timeout=30000)
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).not_to_be_visible()
    style = page.get_by_label('Native local declaration', exact=True)
    style.click()
    page.get_by_role('option', name='csharp-var', exact=True).click()
    page.keyboard.press('Control+s')
    page.wait_for_function("args => JSON.parse(localStorage.getItem('vvs_project_' + args[0])).documents[args[1]].nodes.some(n => n.id === args[2] && n.data.properties?.nativeLocalStyle === 'csharp-var')", arg=[project_id, local_function['id'], declaration['id']])
    expect(code).to_contain_text('var @First = unchecked(((byte)256));', timeout=30000)
    native_type.click()
    assert page.get_by_role('option').all_text_contents() == ['var']
    page.get_by_role('option', name='var', exact=True).click()
    style.click()
    page.get_by_role('option', name='csharp-typed', exact=True).click()
    expect(code).to_contain_text('byte @First = unchecked(((byte)256));', timeout=30000)
    style.click()
    page.get_by_role('option', name='csharp-const', exact=True).click()
    expect(code).to_contain_text('const byte @First = unchecked(((byte)256));', timeout=30000)
    page.keyboard.press('Control+s')
    page.wait_for_function("args => JSON.parse(localStorage.getItem('vvs_project_' + args[0])).documents[args[1]].nodes.some(n => n.data.properties?.nativeLocalStyle === 'csharp-const' && n.data.properties.nativeType === 'byte')", arg=[project_id, local_function['id']])
    page.reload(wait_until='networkidle')
    expect(code).to_contain_text('const byte @First = unchecked(((byte)256));', timeout=30000)
    expect(code).to_contain_text('return Third;')
    # Assignment RHS remains editable, and native narrowing must block/recover.
    saved = page.evaluate(read_project)
    body = saved['documents'][local_function['id']]
    assignment = next(node for node in body['nodes'] if node['data'].get('kindId') == 'variable_set')
    value_edge = next(edge for edge in body['edges'] if edge['target'] == assignment['id'] and edge['targetHandle'] == 'val')
    page.get_by_role('button', name='View', exact=True).click()
    page.get_by_role('button', name='Zoom to fit all', exact=True).click()
    page.locator('.react-flow__node[data-id="' + value_edge['source'] + '"]').click()
    payload = page.get_by_label('Value', exact=True)
    payload.fill('256')
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).to_be_visible(timeout=30000)
    expect(page.get_by_role('button', name='Copy code', exact=True)).to_be_disabled()
    payload.fill('254')
    expect(code).to_contain_text('Third = 254;', timeout=30000)
    payload.fill('255')
    expect(code).to_contain_text('Third = 255;', timeout=30000)
    review = compare(replacement.replace('var Second = First;', 'byte Second = Extra, Extra;'))
    expect(review.get_by_role('alert')).to_be_visible(timeout=30000)
    expect(review.get_by_role('button', name='Apply reviewed re-import')).not_to_be_visible()
    review.get_by_role('button', name='Close', exact=True).click()
    expect(code).to_contain_text('var Second = @First;')
    page.get_by_text('Function: Mutate', exact=True).click()
    expect(code).to_contain_text('Value += 1;', timeout=30000)
    expect(code).to_contain_text('++Value;')
    saved = page.evaluate(read_project)
    mutation_function = next(fn for fn in saved['functions'] if fn['name'] == 'Mutate')
    body = saved['documents'][mutation_function['id']]
    compound = next(node for node in body['nodes'] if node['data'].get('properties', {}).get('assignmentOperator') == '+=')
    prefix = next(node for node in body['nodes'] if node['data'].get('properties', {}).get('assignmentOperator') == '++')
    page.get_by_role('button', name='View', exact=True).click()
    page.get_by_role('button', name='Zoom to fit all', exact=True).click()
    page.locator('.react-flow__node[data-id="' + compound['id'] + '"]').click()
    operator = page.get_by_label('Assignment operator', exact=True)
    operator.click()
    page.get_by_role('option', name='-=', exact=True).click()
    expect(code).to_contain_text('Value -= 1;', timeout=30000)
    rhs = next(edge['source'] for edge in body['edges'] if edge['target'] == compound['id'] and edge['targetHandle'] == 'val')
    page.locator('.react-flow__node[data-id="' + rhs + '"]').click()
    page.get_by_label('Value', exact=True).fill('256')
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).to_be_visible(timeout=30000)
    expect(page.get_by_role('button', name='Copy code', exact=True)).to_be_disabled()
    page.get_by_label('Value', exact=True).fill('1')
    expect(code).to_contain_text('Value -= 1;', timeout=30000)
    page.locator('.react-flow__node[data-id="' + prefix['id'] + '"]').click()
    page.get_by_label('Prefix update', exact=True).uncheck()
    expect(code).to_contain_text('Value++;', timeout=30000)
    page.keyboard.press('Control+s')
    page.wait_for_function("args => { const doc = JSON.parse(localStorage.getItem('vvs_project_' + args[0])).documents[args[1]]; return doc.nodes.some(n => n.id === args[2] && n.data.properties.assignmentOperator === '-=') && doc.nodes.some(n => n.id === args[3] && n.data.properties.prefix === false); }", arg=[project_id, mutation_function['id'], compound['id'], prefix['id']])
    page.reload(wait_until='networkidle')
    expect(code).to_contain_text('Value -= 1;', timeout=30000)
    expect(code).to_contain_text('Value++;')
    page.get_by_text('Function: Parameters', exact=True).click()
    expect(code).to_contain_text('@Input += Initial;', timeout=30000)
    saved = page.evaluate(read_project)
    parameter_function = next(fn for fn in saved['functions'] if fn['name'] == 'Parameters')
    body = saved['documents'][parameter_function['id']]
    setter = next(node for node in body['nodes'] if node['data'].get('kindId') == 'parameter_set' and node['data']['properties']['assignmentOperator'] == '+=')
    assert setter['data']['graphBinding']['kind'] == 'parameter_ref'
    assert not any(variable['name'] == '@Input' for variable in saved['variables'])
    page.get_by_role('button', name='View', exact=True).click()
    page.get_by_role('button', name='Zoom to fit all', exact=True).click()
    page.locator('.react-flow__node[data-id="' + setter['id'] + '"]').click()
    page.get_by_label('Parameter', exact=True).click()
    page.get_by_role('option', name='Count', exact=True).click()
    expect(code).to_contain_text('Count += Initial;', timeout=30000)
    page.keyboard.press('Control+s')
    page.wait_for_function("args => JSON.parse(localStorage.getItem('vvs_project_' + args[0])).documents[args[1]].nodes.some(n => n.id === args[2] && n.data.properties.parameterName === 'Count')", arg=[project_id, parameter_function['id'], setter['id']])
    page.reload(wait_until='networkidle')
    expect(code).to_contain_text('Count += Initial;', timeout=30000)
    main_name = next(tab['name'] for tab in saved['openTabs'] if tab['id'] == 'main-graph')
    page.locator('[draggable="true"] > span.whitespace-nowrap').filter(has_text=main_name).click()
    saved = page.evaluate(read_project)
    definition = next(node for node in saved['documents']['main-graph']['nodes'] if node['data'].get('kindId') == 'function_implement' and node['data'].get('graphBinding', {}).get('symbolId') == parameter_function['id'])
    page.get_by_role('button', name='View', exact=True).click()
    page.get_by_role('button', name='Zoom to fit all', exact=True).click()
    page.locator('.react-flow__node[data-id="' + definition['id'] + '"]').click()
    page.locator('summary').filter(has_text='Native signature').click()
    parameter_type = page.get_by_label('Native type for @Input', exact=True)
    parameter_type.select_option('char')
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).to_be_visible(timeout=30000)
    parameter_type.select_option('byte')
    expect(code).to_contain_text('Count += Initial;', timeout=30000)
    page.get_by_text('Function: Scopes', exact=True).click()
    expect(code).to_contain_text('unchecked {', timeout=30000)
    expect(code).to_contain_text('byte Value = ((byte)256);')
    expect(code).to_contain_text('const byte Limit = ((byte)257);')
    saved = page.evaluate(read_project)
    scope_function = next(fn for fn in saved['functions'] if fn['name'] == 'Scopes')
    body = saved['documents'][scope_function['id']]
    scope_node = next(node for node in body['nodes'] if node['data'].get('kindId') == 'csharp_scope' and node['data'].get('properties', {}).get('overflowContext') == 'unchecked')
    page.get_by_role('button', name='View', exact=True).click()
    page.get_by_role('button', name='Zoom to fit all', exact=True).click()
    page.locator('.react-flow__node[data-id="' + scope_node['id'] + '"]').click()
    scope_context = page.get_by_label('Overflow context', exact=True)
    scope_context.click()
    page.get_by_role('option', name='checked', exact=True).click()
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).to_be_visible(timeout=30000)
    expect(page.get_by_role('button', name='Copy code', exact=True)).to_be_disabled()
    scope_context.click()
    page.get_by_role('option', name='unchecked', exact=True).click()
    expect(code).to_contain_text('unchecked {', timeout=30000)
    page.keyboard.press('Control+s')
    page.wait_for_function("args => JSON.parse(localStorage.getItem('vvs_project_' + args[0])).documents[args[1]].nodes.some(n => n.id === args[2] && n.data.properties.overflowContext === 'unchecked')", arg=[project_id, scope_function['id'], scope_node['id']])
    page.reload(wait_until='networkidle')
    expect(code).to_contain_text('const byte Limit = ((byte)257);', timeout=30000)
    expect(code).to_contain_text('Value += Limit;')
    page.get_by_text('Function: Groups', exact=True).click()
    expect(code).to_contain_text('const byte First = ((byte)256), Second = ((byte)257);', timeout=30000)
    expect(code).to_contain_text('byte Total = First, Copy = Second;')
    saved = page.evaluate(read_project)
    group_function = next(fn for fn in saved['functions'] if fn['name'] == 'Groups')
    body = saved['documents'][group_function['id']]
    group_node = next(node for node in body['nodes'] if node['data'].get('kindId') == 'csharp_declaration_group' and node['data'].get('properties', {}).get('groupStyle') == 'const')
    page.get_by_role('button', name='View', exact=True).click()
    page.get_by_role('button', name='Zoom to fit all', exact=True).click()
    page.locator('.react-flow__node[data-id="' + group_node['id'] + '"]').click()
    group_type = page.get_by_label('Native type', exact=True)
    group_type.click()
    page.get_by_role('option', name='long', exact=True).click()
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).to_be_visible(timeout=30000)
    group_type.click()
    page.get_by_role('option', name='byte', exact=True).click()
    expect(code).to_contain_text('const byte First = ((byte)256), Second = ((byte)257);', timeout=30000)
    group_style = page.get_by_label('Group style', exact=True)
    group_style.click()
    page.get_by_role('option', name='typed', exact=True).click()
    expect(code).to_contain_text('byte First = ((byte)256), Second = ((byte)257);', timeout=30000)
    group_style.click()
    page.get_by_role('option', name='const', exact=True).click()
    expect(code).to_contain_text('const byte First = ((byte)256), Second = ((byte)257);', timeout=30000)
    page.keyboard.press('Control+s')
    page.wait_for_function("args => JSON.parse(localStorage.getItem('vvs_project_' + args[0])).documents[args[1]].nodes.some(n => n.id === args[2] && n.data.properties.groupStyle === 'const' && n.data.properties.nativeType === 'byte')", arg=[project_id, group_function['id'], group_node['id']])
    page.reload(wait_until='networkidle')
    expect(code).to_contain_text('const byte First = ((byte)256), Second = ((byte)257);', timeout=30000)
    saved = page.evaluate(read_project)
    members = [node for node in saved['documents'][group_function['id']]['nodes'] if node['data'].get('properties', {}).get('groupOwnerId') == group_node['id']]
    assert len(members) == 2 and all(node['data']['properties']['nativeType'] == 'byte' and node['data']['properties']['nativeLocalStyle'] == 'csharp-const' for node in members)
    assert all(next(variable for variable in saved['variables'] if variable['id'] == node['data']['properties']['symbolId'])['flags']['readonly'] for node in members)
    page.get_by_text('Function: Definite', exact=True).click()
    expect(code).to_contain_text('int First, Second = Input;', timeout=30000)
    expect(code).to_contain_text('First = Second;')
    saved = page.evaluate(read_project)
    definite_function = next(fn for fn in saved['functions'] if fn['name'] == 'Definite')
    body = saved['documents'][definite_function['id']]
    initialized = next(node for node in body['nodes'] if node['data'].get('kindId') == 'var_define' and node['data'].get('properties', {}).get('name') == 'Value')
    page.get_by_role('button', name='View', exact=True).click()
    page.get_by_role('button', name='Zoom to fit all', exact=True).click()
    page.locator('.react-flow__node[data-id="' + initialized['id'] + '"]').click()
    initializer_toggle = page.get_by_label('Local initializer', exact=True)
    initializer_toggle.uncheck()
    expect(code).to_contain_text('int Value;', timeout=30000)
    expect(code).to_contain_text('Value = Input;')
    initializer_toggle.check()
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).to_be_visible(timeout=30000)
    initializer_toggle.uncheck()
    expect(code).to_contain_text('int Value;', timeout=30000)
    page.keyboard.press('Control+s')
    page.wait_for_function("args => JSON.parse(localStorage.getItem('vvs_project_' + args[0])).documents[args[1]].nodes.some(n => n.id === args[2] && n.data.properties.hasInitializer === false)", arg=[project_id, definite_function['id'], initialized['id']])
    page.reload(wait_until='networkidle')
    expect(code).to_contain_text('int Value;', timeout=30000)
    saved = page.evaluate(read_project)
    body = saved['documents'][definite_function['id']]
    inferred = next(node for node in body['nodes'] if node['data'].get('kindId') == 'var_define' and node['data'].get('properties', {}).get('name') == 'Inferred')
    page.get_by_role('button', name='View', exact=True).click()
    page.get_by_role('button', name='Zoom to fit all', exact=True).click()
    page.locator('.react-flow__node[data-id="' + inferred['id'] + '"]').click()
    style = page.get_by_label('Native local declaration', exact=True)
    style.click()
    page.get_by_role('option', name='csharp-typed', exact=True).click()
    expect(code).to_contain_text('int Inferred = Input;', timeout=30000)
    page.keyboard.press('Control+s')
    page.wait_for_function("args => JSON.parse(localStorage.getItem('vvs_project_' + args[0])).documents[args[1]].nodes.some(n => n.id === args[2] && n.data.properties.nativeLocalStyle === 'csharp-typed' && n.data.properties.nativeType === 'int')", arg=[project_id, definite_function['id'], inferred['id']])
    page.reload(wait_until='networkidle')
    expect(code).to_contain_text('int Inferred = Input;', timeout=30000)
    expect(code).to_contain_text('int Value;')
    page.get_by_text('Function: Boolean', exact=True).click()
    expect(code).to_contain_text('public static bool Boolean(int Input)', timeout=30000)
    expect(code).to_contain_text('false')
    expect(code).to_contain_text('&&')
    saved = page.evaluate(read_project)
    boolean_function = next(fn for fn in saved['functions'] if fn['name'] == 'Boolean')
    body = saved['documents'][boolean_function['id']]
    comparison = next(node for node in body['nodes'] if node['data'].get('properties', {}).get('operator') == '<')
    page.get_by_role('button', name='View', exact=True).click()
    page.get_by_role('button', name='Zoom to fit all', exact=True).click()
    page.locator('.react-flow__node[data-id="' + comparison['id'] + '"]').click()
    boolean_operator = page.get_by_label('Operator', exact=True)
    boolean_operator.click()
    page.get_by_role('option', name='&&', exact=True).click()
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).to_be_visible(timeout=30000)
    boolean_operator.click()
    page.get_by_role('option', name='>=', exact=True).click()
    expect(code).to_contain_text('Value >= 0', timeout=30000)
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).not_to_be_visible()
    page.keyboard.press('Control+s')
    page.wait_for_function("args => JSON.parse(localStorage.getItem('vvs_project_' + args[0])).documents[args[1]].nodes.some(n => n.id === args[2] && n.data.properties.operator === '>=')", arg=[project_id, boolean_function['id'], comparison['id']])
    page.reload(wait_until='networkidle')
    expect(code).to_contain_text('public static bool Boolean(int Input)', timeout=30000)
    expect(code).to_contain_text('Value >= 0')
    print('C# Boolean graphs: literal/comparison/logical Code panel, native invalid/recovery operator editing and save/reload passed', flush=True)
    print('C# definite assignment: mixed groups, ancestor initialization, no default initializer, empty-pin rejection/recovery, parameter-derived style and saved/reloaded Code panel passed', flush=True)
    print('C# declaration groups: exact comma syntax, native type invalid/recovery, atomic type/style/readonly editing and saved/reloaded Code panel passed', flush=True)
    print('C# lexical scopes: inherited unchecked context, scope inspector invalid/recovery, nested locals, saved/reloaded Code panel passed', flush=True)
    print('C# parameter writes: own signature slots, inspector retarget/save/reload and invalid native signature/recovery passed', flush=True)
    print('C# mutation inspector: compound operator edit, invalid native RHS/recovery, prefix/postfix editing and saved/reloaded Code panel passed', flush=True)
    print('C# locals: actual import, exact typed/var/const Code panel, type/style editing with inferred width and readonly identity, invalid promotion/recovery, save/reload and atomic invalid forward-group rejection passed', flush=True)
    print('C# source import: deployed worker review/acceptance, editable signatures, invalid edit/recovery, reload/tab fidelity, graph-only reimport, both conflict choices, source replacement and unsupported-addition blocking passed', flush=True)
    context.close()


def verify_csharp_signatures(browser, base_url):
    """Trusted saved graph: exercise actual Code panel, inspector and persistence."""
    graph = json.loads((Path(__file__).resolve().parents[3] / 'packages/transpiler/test/csharp-signature.fixture.json').read_text(encoding='utf-8'))
    function_id = 'identity-byte'
    definitions = [node for node in graph['nodes'] if node['id'] in ['class', function_id + '-declare', function_id + '-define']]
    for index, node in enumerate(definitions):
        node['position'] = {'x': index * 280, 'y': 0}
    node_ids = {node['id'] for node in definitions}
    home = {'nodes': definitions, 'edges': [edge for edge in graph['edges'] if edge['source'] in node_ids and edge['target'] in node_ids]}
    # The all-type fixture's byte declaration follows sbyte; rebuild its visible class edge.
    home['edges'].append({'id': 'class-byte', 'source': 'class', 'target': function_id + '-declare', 'sourceHandle': 'exec_out', 'targetHandle': 'exec_in', 'type': 'vvs_standard_edge', 'data': {'pinType': 'execution'}})
    project_id = 'proj-native-csharp-signature-browser'
    snapshot = {
        'version': 3, 'projectId': project_id, 'savedAt': '',
        'projectDetails': {'moduleName': graph['moduleName'], 'extendsType': '', 'description': 'Trusted native signature graph fixture'},
        'targetLanguage': 'csharp', 'autoCompile': True, 'autoSave': True,
        'variables': [], 'events': [], 'functions': [fn for fn in graph['functions'] if fn['id'] == function_id],
        'documents': {'main-graph': home, function_id: graph['documents'][function_id]},
        'classes': graph['classes'], 'activeClassId': graph['activeClassId'],
        'graphContainers': [{'id': 'main-graph', 'name': graph['moduleName']}],
        'openTabs': [{'id': 'main-graph', 'type': 'container', 'name': graph['moduleName']}, {'id': function_id, 'type': 'function', 'name': 'Function: Identity_byte'}],
        'activeGraphTab': 'main-graph', 'installedLibrary': [], 'targetFileExtensions': {},
    }
    context = browser.new_context()
    page = context.new_page()
    page.goto(base_url + '/', wait_until='networkidle')
    page.evaluate("snapshot => localStorage.setItem('vvs_project_' + snapshot.projectId, JSON.stringify(snapshot))", snapshot)
    page.goto(base_url + '/editor?id=' + project_id, wait_until='networkidle')
    welcome = page.get_by_role('dialog').filter(has=page.locator('#graph-help-title'))
    expect(welcome).to_be_visible(timeout=30000)
    welcome.get_by_role('button', name='Close', exact=True).click()
    code = page.locator('.cm-content').first
    expect(code).to_contain_text('public static byte Identity_byte(byte value)', timeout=30000)
    expect(code).to_contain_text('return value;')
    page.locator('.react-flow__node[data-id="identity-byte-define"]').click()
    page.locator('summary').filter(has_text='Native signature').click()
    parameter = page.get_by_label('Native type for value', exact=True)
    result = page.get_by_label('Native return type', exact=True)
    expect(parameter).to_have_value('byte')
    expect(result).to_have_value('byte')
    expect(page.get_by_label('Mode for value', exact=True)).to_be_disabled()
    expect(page.get_by_label('Default for value', exact=True)).to_be_disabled()
    assert parameter.locator('option').all_text_contents() == ['sbyte', 'byte', 'short', 'ushort', 'int', 'uint', 'long', 'ulong', 'char']
    parameter.select_option('int')
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).to_be_visible(timeout=30000)
    expect(page.get_by_role('button', name='Copy code', exact=True)).to_be_disabled()
    parameter.select_option('byte')
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).not_to_be_visible(timeout=30000)
    result.select_option('ushort')
    expect(code).to_contain_text('public static ushort Identity_byte(byte value)', timeout=30000)
    page.keyboard.press('Control+s')
    page.wait_for_function("id => JSON.parse(localStorage.getItem('vvs_project_' + id)).documents['main-graph'].nodes.some(n => n.id === 'identity-byte-define' && n.data.properties.nativeReturnType === 'ushort')", arg=project_id)
    page.reload(wait_until='networkidle')
    expect(code).to_contain_text('public static ushort Identity_byte(byte value)', timeout=30000)
    page.get_by_text('Function: Identity_byte', exact=True).click()
    expect(code).to_contain_text('public static ushort Identity_byte(byte value)', timeout=30000)
    expect(code).to_contain_text('return value;')
    assert 'float ' not in code.inner_text()
    print('C# signature inspector: exact native Code panel, invalid narrowing/recovery, widening, save/reload and function-tab fidelity passed', flush=True)
    expression = json.loads((Path(__file__).resolve().parents[3] / 'packages/transpiler/test/csharp-expression.fixture.json').read_text(encoding='utf-8'))
    snapshot['functions'] = expression['functions']
    snapshot['documents'] = {**expression['documents'], 'main-graph': {'nodes': expression['nodes'], 'edges': expression['edges']}}
    snapshot['openTabs'] = [{'id': 'main-graph', 'type': 'container', 'name': expression['moduleName']}, {'id': 'identity-int', 'type': 'function', 'name': 'Function: Evaluate'}]
    snapshot['activeGraphTab'] = 'identity-int'
    page.evaluate("snapshot => localStorage.setItem('vvs_project_' + snapshot.projectId, JSON.stringify(snapshot))", snapshot)
    page.reload(wait_until='networkidle')
    expect(code).to_contain_text('return unchecked(((byte)256));', timeout=30000)
    page.locator('.react-flow__node[data-id="expression-0"]').click()
    overflow = page.get_by_label('Overflow context', exact=True)
    expect(overflow).to_be_visible()
    overflow.click()
    page.get_by_role('option', name='checked', exact=True).click()
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).to_be_visible(timeout=30000)
    expect(page.get_by_role('button', name='Copy code', exact=True)).to_be_disabled()
    overflow.click()
    page.get_by_role('option', name='unchecked', exact=True).click()
    expect(code).to_contain_text('return unchecked(((byte)256));', timeout=30000)
    expect(page.get_by_role('alert').filter(has_text='Code generation blocked')).not_to_be_visible()
    page.keyboard.press('Control+s')
    page.wait_for_function("id => JSON.parse(localStorage.getItem('vvs_project_' + id)).documents['identity-int'].nodes.some(n => n.id === 'expression-0' && n.data.properties.payload === 'unchecked')", arg=project_id)
    page.reload(wait_until='networkidle')
    expect(code).to_contain_text('return unchecked(((byte)256));', timeout=30000)
    print('C# integral expression inspector: exact cast tokens, checked-overflow invalid edit/recovery, save/reload and Code-panel fidelity passed', flush=True)
    context.close()
