"""Live local worker import, coordinated inspector recovery, persistence and reimport."""
import json
from pathlib import Path
from playwright.sync_api import expect


def verify_native_local_imports(browser, base_url):
    cases = json.loads((Path(__file__).resolve().parents[3] / 'packages/source-import/test/native-local-source-cases.json').read_text(encoding='utf-8'))
    for language in ['cpp', 'rust', 'gdscript']:
        source = cases[language][0]['source']
        file_name = 'locals.' + {'cpp': 'cpp', 'rust': 'rs', 'gdscript': 'gd'}[language]
        context = browser.new_context()
        page = context.new_page()
        errors = []
        page.on('pageerror', lambda error: errors.append(str(error)))
        page.goto(base_url + '/', wait_until='networkidle')
        page.get_by_role('button', name='Import source…').first.click()
        dialog = page.locator('dialog')
        dialog.get_by_label('Language', exact=False).select_option(language)
        dialog.locator('input[type=file]').set_input_files({'name': file_name, 'mimeType': 'text/plain', 'buffer': source.encode('utf-8')})
        dialog.get_by_role('button', name='Analyze source').click()
        dialog.get_by_role('button', name='Mapping candidate', exact=False).click()
        dialog.get_by_role('button', name='Build and validate preview').click()
        accept = dialog.get_by_role('button', name='Accept as new project')
        expect(accept).to_be_enabled(timeout=30000)
        accept.click()
        page.wait_for_url('**/editor?**', wait_until='networkidle')
        welcome = page.get_by_role('dialog').filter(has=page.locator('#graph-help-title'))
        expect(welcome).to_be_visible(timeout=30000)
        welcome.get_by_role('button', name='Close', exact=True).click()
        code = page.locator('.cm-content').first
        expect(code).to_contain_text('first * 2', timeout=30000)
        saved = page.evaluate("language => Object.keys(localStorage).filter(k => k.startsWith('vvs_project_')).map(k => JSON.parse(localStorage.getItem(k))).find(p => p.targetLanguage === language)", language)
        assert len(saved['functions']) == 3 and len(saved['variables']) == 5
        project_id = saved['projectId']
        fn = next(fn for fn in saved['functions'] if fn['name'] == 'accumulate')
        definition = next(node for node in saved['documents']['main-graph']['nodes'] if node['data'].get('graphBinding', {}).get('symbolId') == fn['id'])
        page.get_by_role('button', name='View', exact=True).click()
        page.get_by_role('button', name='Zoom to fit all', exact=True).click()
        page.locator('.react-flow__node[data-id="' + definition['id'] + '"]').dblclick()
        body = saved['documents'][fn['id']]
        declaration = next(node for node in body['nodes'] if node['data']['kindId'] == 'var_define' and node['data']['properties']['name'] == 'result')
        page.get_by_role('button', name='View', exact=True).click()
        page.get_by_role('button', name='Zoom to fit all', exact=True).click()
        page.locator('.react-flow__node[data-id="' + declaration['id'] + '"]').click()
        page.locator('summary').filter(has_text='Native local declaration').click()
        mode = page.get_by_label('Native local mode', exact=True)
        mode.select_option('inferred')
        expect(code).to_contain_text({'cpp': 'auto result =', 'rust': 'let mut result =', 'gdscript': 'var result :='}[language], timeout=30000)
        expect(page.get_by_label('Native local type', exact=True)).not_to_be_visible()
        page.keyboard.press('Control+s')
        page.wait_for_function("args => Object.values(JSON.parse(localStorage.getItem('vvs_project_' + args[0])).documents).some(d => d.nodes.some(n => n.id === args[1] && n.data.properties?.nativeInferenceMode))", arg=[project_id, declaration['id']])
        page.reload(wait_until='networkidle')
        expect(code).to_contain_text({'cpp': 'auto result =', 'rust': 'let mut result =', 'gdscript': 'var result :='}[language], timeout=30000)
        page.get_by_role('button', name='View', exact=True).click()
        page.get_by_role('button', name='Zoom to fit all', exact=True).click()
        page.locator('.react-flow__node[data-id="' + declaration['id'] + '"]').click()
        page.locator('summary').filter(has_text='Native local declaration').click()
        mode.select_option('typed')
        expect(page.get_by_label('Native local type', exact=True)).to_be_visible()
        name = page.get_by_label('Native local name', exact=True)
        name.fill('editedResult')
        name.press('Tab')
        expect(code).to_contain_text('editedResult', timeout=30000)
        mutable = page.get_by_label('Mutable local', exact=True)
        mutable.uncheck()
        blocked = page.get_by_role('alert').filter(has_text='Code generation blocked')
        expect(blocked).to_be_visible(timeout=30000)
        expect(page.get_by_role('button', name='Copy code', exact=True)).to_be_disabled()
        if language in ['cpp', 'rust']:
            # An unrelated readonly assignment must not prevent an independently
            # valid initializer from entering inferred mode. Generation stays
            # blocked through the mode change and actual persisted reload.
            mode.select_option('inferred')
            expect(mode).to_have_value('inferred')
            expect(blocked).to_be_visible()
            expect(page.get_by_label('Native local type', exact=True)).not_to_be_visible()
            page.keyboard.press('Control+s')
            page.wait_for_function("args => Object.values(JSON.parse(localStorage.getItem('vvs_project_' + args[0])).documents).some(d => d.nodes.some(n => n.id === args[1] && n.data.properties?.nativeInferenceMode && n.data.properties?.nativeMutable === false))", arg=[project_id, declaration['id']])
            page.reload(wait_until='networkidle')
            expect(blocked).to_be_visible(timeout=30000)
            page.get_by_role('button', name='View', exact=True).click()
            page.get_by_role('button', name='Zoom to fit all', exact=True).click()
            page.locator('.react-flow__node[data-id="' + declaration['id'] + '"]').click()
            page.locator('summary').filter(has_text='Native local declaration').click()
            expect(mode).to_have_value('inferred')
            mutable.check()
            expect(blocked).not_to_be_visible(timeout=30000)
            expect(code).to_contain_text('editedResult', timeout=30000)
            mode.select_option('typed')
        mutable.check()
        expect(blocked).not_to_be_visible(timeout=30000)
        native_type = page.get_by_label('Native local type', exact=True)
        native_type.select_option('bool')
        expect(blocked).to_be_visible(timeout=30000)
        page.keyboard.press('Control+s')
        page.wait_for_function("args => JSON.parse(localStorage.getItem('vvs_project_' + args[0])).variables.some(v => v.id === args[1] && v.type === 'data_boolean' && v.typeRef.id === 'data_boolean')", arg=[project_id, declaration['data']['properties']['symbolId']])
        page.reload(wait_until='networkidle')
        expect(blocked).to_be_visible(timeout=30000)
        page.get_by_role('button', name='View', exact=True).click()
        page.get_by_role('button', name='Zoom to fit all', exact=True).click()
        page.locator('.react-flow__node[data-id="' + declaration['id'] + '"]').click()
        page.locator('summary').filter(has_text='Native local declaration').click()
        native_type.select_option('i32' if language == 'rust' else 'int')
        expect(blocked).not_to_be_visible(timeout=30000)
        page.keyboard.press('Control+s')
        page.wait_for_function("args => JSON.parse(localStorage.getItem('vvs_project_' + args[0])).variables.some(v => v.id === args[1] && v.name === 'editedResult')", arg=[project_id, declaration['data']['properties']['symbolId']])
        page.reload(wait_until='networkidle')
        expect(code).to_contain_text('editedResult', timeout=30000)

        def compare(text):
            page.get_by_role('button', name='File', exact=True).click()
            page.get_by_role('button', name='Re-import source…', exact=True).click()
            review = page.locator('dialog')
            review.get_by_label('Imported file', exact=True).fill(file_name)
            review.get_by_label('Updated source', exact=True).fill(text)
            review.get_by_role('button', name='Compare source and graph').click()
            return review

        review = compare(source)
        expect(review.get_by_role('button', name='Apply reviewed re-import')).to_be_enabled(timeout=30000)
        expect(review.get_by_label('Resolve this file')).not_to_be_visible()
        review.get_by_role('button', name='Apply reviewed re-import').click()
        expect(code).to_contain_text('editedResult', timeout=30000)
        incoming = source.replace('* 2', '* 4')
        for choice, expected in [('keep-graph', 'editedResult'), ('use-source', 'first * 4')]:
            review = compare(incoming)
            expect(review.get_by_label('Resolve this file')).to_be_visible(timeout=30000)
            expect(review.get_by_role('button', name='Apply reviewed re-import')).to_be_disabled()
            review.get_by_label('Resolve this file').select_option(choice)
            review.get_by_role('button', name='Apply reviewed re-import').click()
            expect(code).to_contain_text(expected, timeout=30000)
        page.keyboard.press('Control+s')
        page.wait_for_function("args => Object.values(JSON.parse(localStorage.getItem('vvs_project_' + args[0])).documents).some(d => d.nodes.some(n => n.data.properties?.sourceImport?.source === args[1]))", arg=[project_id, incoming])
        page.reload(wait_until='networkidle')
        expect(code).to_contain_text('first * 4', timeout=30000)
        assert not errors, errors
        print(language + ': local worker import, mode switch/inferred save-reload and rename/readonly/type recovery (including invalid mode reload), save/reload and both reimport choices passed', flush=True)
        context.close()
