/** Trusted native adapter fixtures; imported source is parsed/type-checked, never run. */
export const GO_UNIT_FIXTURES = [
  "package sample\nfunc check() bool { return true }\nfunc conditional(flag bool) bool { return flag && check() }",
  "package sample\nfunc check(flag bool) bool { return flag }\nfunc either(first bool, second bool) bool { return check(first) || check(second) }",
  "package sample\nfunc check(flag bool) bool { return flag }\nfunc nested(first bool, second bool, third bool) bool { return check(first) || (check(second) && check(third)) }",
  "package sample\nfunc check() bool { return true }\nfunc repeated(flag bool) bool { return flag && (check() && check()) }",
  "package sample\nfunc value(input int) int { return input + 1 }\nfunc compare(flag bool, input int) bool { return flag && (value(input) > value(0)) }",
  "package sample\nfunc check(flag bool) bool { return flag }\nfunc argument(first bool, second bool) bool { return first && check(check(second)) }",
  "package sample\nfunc positive(value int) bool { return value >= 0 }\nfunc count(limit int) int { count := 0; for count < limit && positive(count) { count++ }; return count }",
  "package sample\nfunc check(flag bool) bool { return flag }\nfunc constant(flag bool) bool { const enabled = true; return enabled && check(flag) }",

  'package sample\nfunc identity(value float64) float64 { return value }',
  'package sample\nfunc identity(value string) string { return value }',
  'package sample\nfunc identity(value bool) bool { return value }',
  'package sample\nfunc choose(flag bool, first string, second string) string { if flag { return first } else { return second } }',
  'package sample\nfunc scale(value float64) float64 { return value * 2 }\nfunc pipeline(value float64) float64 { return scale(value + 1) }',
  'package sample\nfunc message() string { return "emoji 🧬" }',
  'package sample\nfunc compare(left float64, right float64) bool { return left < right }',
  'package sample\nfunc compare(left bool, right bool) bool { return left == right }',
  'package sample\nfunc compare(left string, right string) bool { return left >= right }',
  'package sample\nfunc empty() { return }',
  'package sample\nfunc doubled(value float64) float64 { copy := value * 2; return copy }',
  'package sample\nfunc typed(value float64) float64 { var copy float64 = 0; copy = value; return copy }',
  'package sample\nfunc text(value string) string { copy := value; copy = "updated"; return copy }',
  'package sample\nfunc flag(value bool) bool { var copy bool = false; copy = value; return copy }',
  'package sample\nfunc advance(value float64) float64 { copy := value; copy++; copy--; copy += 2; return copy }',
  'package sample\nfunc conditional(flag bool, value float64) float64 { copy := value; if flag { copy += 2 }; return copy }',
  'package sample\nfunc repeated(value float64, limit float64) float64 { copy := value; for copy < limit { copy++ }; return copy }',
  'package sample\nfunc counted(start float64, limit float64) float64 { var total float64 = 0; for index := start; index < limit; index++ { total += index }; return total }',
  'package sample\nfunc flow(start float64, limit float64) float64 { var total float64 = 0; for index := start; index < limit; index++ { if index == 2 { continue }; if index > 4 { break }; total += index }; return total }',
  'package sample\nfunc scale(value float64) float64 { return value * 2 }\nfunc pipeline(value float64) float64 { copy := scale(value); for copy < 10 { copy = scale(copy) }; return copy }',
  'package sample\nfunc nested(start float64, limit float64) float64 { var total float64 = 0; for index := start; index < limit; index++ { for index := start; index < limit; index++ { if index == 2 { continue }; total += index } }; return total }',
  'package sample\nfunc cleanup() { return }\nfunc finish() { cleanup(); return }',
  'package sample\nfunc shadow(flag bool, value float64) float64 { copy := value; if flag { copy := value * 2; return copy } else { return copy } }',

  ...['int8','int16','int32','int64','uint8','uint16','uint32','uint64','byte','rune'].map(type => `package sample\nfunc identity(value ${type}) ${type} { copy := value; copy++; copy--; return copy }\nfunc pipeline(value ${type}) ${type} { var copy ${type} = identity(value); copy = value; return identity(copy) }`),
  'package sample\nfunc divide(left int64, right int64) int64 { return left / right }',
  'package sample\nfunc aliases(left byte, right uint8) uint8 { return left + right }',
  'package sample\nfunc counted(start int16, limit int16) int16 { total := start; for index := start; index < limit; index++ { total += index }; return total }',

  'package sample\nfunc count(value int64) int64 { return value + 1 }',
  'package sample\nfunc limit() uint64 { return 0xffff_ffff_ffff_ffff }',
  'package sample\nfunc minimum() int64 { return -9223372036854775808 }',
  'package sample\nfunc arithmetic() int { return 9 / 2 + 7 % 3 }',
  'package sample\nfunc complement(value uint8) uint8 { return ^value &^ 0x0f }',
  'package sample\nfunc shifted(value uint64, count uint8) uint64 { return (value << count) | 1 }',
  'package sample\nfunc repeated(value int64) int64 { copy := value; copy += 2; copy /= 3; return copy }',
  'package sample\nfunc counted(limit int) int { total := 0; for index := 0; index < limit; index++ { if index == 2 { continue }; total += index }; return total }',
  'package sample\nfunc accept(value uint64) uint64 { return value }\nfunc maximum() uint64 { return accept(18446744073709551615) }',
  'package sample\nfunc radix() int { return 0b_1010 + 0o_12 + 012 + 0x_a }',
  'package sample\nfunc constant() uint64 { return 1 << 63 }',
  'package sample\nfunc explicit() int8 { var value int8 = -128; return value }',
  'package sample\nfunc compare(value uint64) bool { return value < 18446744073709551615 }',
  'package sample\nfunc truncate() float64 { return 1 / 2 }',

  "package sample\nfunc identity(value float32) float32 { copy := value; copy += .1; copy *= 2; return copy }\nfunc pipeline(value float32) float32 { return identity(value) }",
  "package sample\nfunc rounded() float32 { var value float32 = 16777217.0; return value }",
  "package sample\nfunc compare(value float32) bool { return value < .1 }",
  "package sample\nfunc convert(value int64) uint8 { return uint8(value) }",
  "package sample\nfunc convert(value float64) int32 { return int32(value) }",
  "package sample\nfunc convert(value uint64) float32 { return float32(value) }",
  "package sample\nfunc convert(value float32) float64 { return float64(value) }",
  "package sample\nfunc constant() float64 { return float64(float32(.1)) }",
  "package sample\nfunc constant() int8 { return int8(uint8(127)) }",
  "package sample\nfunc constant() float32 { return float32(9007199254740993) }",
  "package sample\nfunc shifted(count uint8) uint64 { return uint64(1 << count) }",
  "package sample\nfunc mixed(limit int) float32 { var total float32 = 0; for index := 0; index < limit; index++ { total += float32(index) / 10; if total > 2 { break } }; return total }",
  "package sample\nfunc negative(value float32) float32 { return -value }",
  "package sample\nfunc comparison(left float32, right float32) bool { return left == right }",

  "package sample\nfunc sum() float64 { return 1.5 + 2.5 }",
  "package sample\nfunc fraction() float64 { return 1.0 / 10 }",
  "package sample\nfunc hex() float64 { return 0x_1.fp+2 + .5e1 }",
  "package sample\nfunc integral() uint64 { return 18446744073709551615.0 }",
  "package sample\nfunc inferred() float64 { value := 0.1 + 0.2; return value }",
  "package sample\nfunc underflow() float64 { return -1e-1200 }",
  "package sample\nfunc tiny() float64 { return 0x1p-1074 }",
  "package sample\nfunc exact() bool { return (0.1 + 0.2) == 0.3 }",
  "package sample\nfunc count(value int8) int8 { return value + 1.0 }",
  "package sample\nfunc shifted(count uint8) uint64 { return 1.0 << count }",
  "package sample\nfunc shifted() int { return 1.0 << 2.0 }",
  "package sample\nfunc accept(value float64) float64 { return value }\nfunc composed(limit int) float64 { total := 0.0; for index := 0; index < limit; index++ { total += accept(1.0 / 10.0); if total > .5 { break } }; return total }",
  "package sample\nfunc largest() float64 { return 0x1.fffffffffffffp1023 }",

  'package sample\nfunc shifted(count uint8) uint64 { return 1 << count }',
  'package sample\nfunc composed(count uint8) uint8 { return (1 << count) + (2 << count) }',
  'package sample\nfunc complement(count uint8) uint8 { return ^(1 << count) }',
  'package sample\nfunc peer(count uint8, value uint64) uint64 { return (1 << count) + value }',
  'package sample\nfunc count(left uint64, count uint8) uint64 { return left << (1 << count) }',
  'package sample\nfunc signedCount(left uint64, count uint8) uint64 { return left << (-1 << count) }',
  'package sample\nfunc wideCount(left uint64, count uint8) uint64 { return left << (2147483648 << count) }',
  'package sample\nfunc compare(count uint8, value uint64) bool { return (1 << count) > value }',
  'package sample\nfunc accept(value uint8) uint8 { return value }\nfunc caller(count uint8) uint8 { return accept(1 << count) }',
  'package sample\nfunc local(count uint8) uint8 { var value uint8 = 1 << count; value = 2 << count; value += 1 << count; return value }',
  'package sample\nfunc inferred(count uint8) int { value := 1 << count; return value }',
  'package sample\nfunc large(value uint8) uint8 { return value << 18446744073709551615 }',
  'package sample\nfunc constant() int { return -1 >> 1000 }',
  'package sample\nfunc constant() int { return 0 << 1074 }',
  'package sample\nfunc compound(value uint64, count uint8) uint64 { copy := value; copy %= 7; copy &= 0xff; copy |= 1; copy ^= 2; copy &^= 4; copy <<= count; copy >>= count; return copy }',

  // Exact typed/untyped constant bindings and increasingly composed uses.
  "package sample\nfunc exact() uint64 { const maximum = 18446744073709551615; return maximum }",
  "package sample\nfunc ratio() float64 { const third = 1.0 / 3.0; const twice = third + third; return twice }",
  "package sample\nfunc typed() float32 { const tenth float32 = .1; const doubled = tenth + tenth; return doubled }",
  "package sample\nfunc retained() float64 { const tenth float32 = .1; return float64(tenth) }",
  "package sample\nfunc boundary() int32 { const boundary int32 = 2147483647; return boundary }",
  "package sample\nfunc shifts(count uint8) uint64 { const one = 1; return one << count }",
  "package sample\nfunc bits() uint8 { const mask uint8 = 0xff; const bits = mask &^ 3; return bits }",
  "package sample\nfunc truncation() int { const half = 5 / 2; return half }",
  "package sample\nfunc boolConst() bool { const equal = 1.0 / 3.0 < 0.5; const enabled = !false && equal; return enabled || false }",
  "package sample\nfunc roundedComparison() bool { const exact float32 = 16777217.0; const equal = exact == 16777217; return equal }",
  "package sample\nfunc mixedComparison() bool { const typed int8 = 7; const equal = typed == 7.0; return equal }",
  "package sample\nfunc dynamicCompare(value float64) bool { const threshold = .1; return value > threshold }",
  "package sample\nfunc text() string { const greeting = \"hello\" + \" world\"; return greeting }",
  "package sample\nfunc typedText() string { const prefix string = \"result: \"; const text = prefix + \"ok\"; return text }",
  "package sample\nfunc scalarText() bool { const same = \"a\" == \"a\"; return same }",
  "package sample\nfunc orderedText() bool { const ordered = \"𐀀\" > \"\"; return ordered }",
  "package sample\nfunc unused() int { const unused = 18446744073709551615; return 1 }",
  "package sample\nfunc shadow(flag bool) int { const limit = 5; if flag { const limit = 7; return limit }; return limit }",
  "package sample\nfunc inferred() int { const value = 2; copy := value; copy += value; return copy }",
  "package sample\nfunc typedLocal() uint8 { const value = 255; var copy uint8 = value; return copy }",
  "package sample\nfunc accept(value float32) float32 { return value }\nfunc called() float32 { const value float32 = 0.1; return accept(value) }",
  "package sample\nfunc composed(limit int) float64 { const step = 1.0 / 10.0; total := 0.0; for index := 0; index < limit; index++ { const ceiling = .5; total += step; if total > ceiling { break } }; return total }",
  "package sample\nfunc boolean(value bool) bool { const flag bool = true; return value && flag }",
  "package sample\nfunc textUpdate(value string) string { const suffix = \"!\"; copy := value; copy += suffix; return copy }",

];

/** Native constructs exposed by increasingly complex inputs; none are silently accepted. */
export const GO_UNIT_GAPS = [
  {"id": "go-package-constants", "source": "package sample\nconst limit = 7\nfunc read() int { return limit }", "requirement": "File-owned constant member declarations and cross-function name closure", "roadmapId": "u93-module-projects"},
  {"id": "go-constant-groups-iota", "source": "package sample\nfunc read() int { const ( first = iota; second ); return second }", "requirement": "Visible constant declaration groups, omitted initializer repetition and group-local iota index", "roadmapId": "u93-scoped-locals"},
  {"id": "go-defined-numeric-type", "source": "package sample\ntype Count int32\nfunc read(value Count) Count { return value }", "requirement": "Defined native type identity and explicit conversions, distinct from aliases", "roadmapId": "u93-class-semantics"},
  {"id": "go-type-alias", "source": "package sample\ntype Count = int32\nfunc read(value Count) Count { return value }", "requirement": "Visible native aliases and lexical type-name binding closure", "roadmapId": "u93-class-semantics"},
  {"id": "go-byte-string", "source": "package sample\nfunc text() string { const text = \"\\xff\"; return text }", "requirement": "Native Go byte strings and escapes without Unicode/JSON reinterpretation", "roadmapId": "u93-native-values"},

  { id: 'go-composed-shift-count', source: 'package sample\nfunc count(left uint64, count uint8) uint64 { return left << ((1 << count) + 2) }', requirement: 'Untyped nonconstant shift-count composition with independent compiler evidence; go/types alone leaves count operands unresolved', roadmapId: 'u93-scoped-locals' },
  { id: 'go-big-float-constant', source: 'package sample\nfunc ratio() float64 { return 1e1400 / 1e1400 }', requirement: 'Pinned 512-bit big.Float fallback outside the native rational component domain', roadmapId: 'u93-scoped-locals' },
  { id: 'go-multi-bindings', source: 'package sample\nfunc paired(value float64) float64 { first, second := value, value; return first + second }', requirement: 'Multi-name declaration/redeclaration, ordered evaluation and simultaneous binding', roadmapId: 'u93-scoped-locals' },
  { id: 'go-multiple-results', source: 'package sample\nfunc pair(value float64) (float64, bool) { return value, true }', requirement: 'Ordered native result tuples and call destructuring', roadmapId: 'u93-resolved-calls' },
  { id: 'go-range-loop', source: 'package sample\nfunc sum() float64 { var total float64 = 0; for _, value := range []float64{1, 2} { total += value }; return total }', requirement: 'Native slices, ordered iteration and multi-binding range index/value semantics', roadmapId: 'u93-control-flow' },
  { id: 'go-defer', source: 'package sample\nfunc cleanup() { return }\nfunc finish() { defer cleanup(); return }', requirement: 'Function-exit LIFO cleanup with argument capture timing', roadmapId: 'u93-control-flow' },
  { id: 'go-channels', source: 'package sample\nfunc receive() bool { ch := make(chan bool, 1); go func() { ch <- true }(); return <-ch }', requirement: 'Channel types, goroutine closures, send/receive effects and concurrency', roadmapId: 'u93-control-flow' },
  { id: 'go-receiver', source: 'package sample\ntype Counter struct { value float64 }\nfunc (counter Counter) read() float64 { return counter.value }', requirement: 'Visible type declarations, fields and value/pointer receiver binding', roadmapId: 'u93-class-semantics' },
  { id: 'go-import-context', source: 'package sample\nimport "math"\nfunc root(value float64) float64 { return math.Sqrt(value) }', requirement: 'Visible imports and package/toolchain dependency signature closure', roadmapId: 'u93-module-projects' },
  { id: 'go-comments', source: 'package sample\n// Identity keeps its native value.\nfunc identity(value float64) float64 { return value }', requirement: 'Owned comments, trivia and targeted re-import preservation', roadmapId: 'u93-trivia-reimport' },
];

export const GO_WORD_FIXTURES = [
  { wordBits: 32 as const, source: 'package sample\nfunc boundary() int { copy := 2147483647; return copy }' },
  { wordBits: 64 as const, source: 'package sample\nfunc boundary() int { copy := 2147483648; return copy }' },
  { wordBits: 32 as const, source: 'package sample\nfunc address() uintptr { return 0xffff_ffff }' },
  { wordBits: 64 as const, source: 'package sample\nfunc address() uintptr { return 0xffff_ffff_ffff_ffff }' },
];
