import type { NativeValueProfile } from './nativeValues';

/** Trusted native-value contract probes, certified separately from token inventory. */
export const NATIVE_VALUE_CORPUS: readonly { id: string; profile: NativeValueProfile; source: string; featureIds: string[]; requirement: string }[] = [
  { id: 'js-exact-scalars', profile: 'javascript.es2022', source: 'function values() { return [-0, 9007199254740993n, 1e309, null, true]; }', featureIds: ['scalar-values', 'numeric-domains', 'collections'], requirement: 'Visible exact Number/BigInt/null values with JSON-safe payloads and ordered array construction' },
  { id: 'py-exact-scalars', profile: 'python.3.11', source: 'def values():\n    return [-0.0, 9007199254740993, 1e309, None, True]\n', featureIds: ['scalar-values', 'numeric-domains', 'collections'], requirement: 'Separate Python arbitrary integers, binary64 floats and None from JS numeric/null domains' },
  { id: 'js-ordered-object', profile: 'javascript.es2022', source: 'function identity(value) { return value; } function build(value) { const values = [identity(value), identity(value)]; const result = { first: values[0], [String(value)]: identity(value) }; return result; }', featureIds: ['collections', 'indexing'], requirement: 'Distinct call evaluations, computed-key/value order and explicit access ownership' },
  { id: 'py-ordered-dict', profile: 'python.3.11', source: 'def identity(value):\n    return value\n\ndef build(value):\n    values = [identity(value), identity(value)]\n    result = {str(value): values[0], "next": identity(value)}\n    return result\n', featureIds: ['collections', 'indexing'], requirement: 'Dict key/value evaluation, list access and resolved repeated-call ownership' },
  { id: 'js-mixed-equality', profile: 'javascript.es2022', source: 'function compare(value) { const items = [0, "0", null]; return items[0] == value; }', featureIds: ['dynamic-operators', 'collections', 'indexing'], requirement: 'Native abstract equality, ToPrimitive/coercion and mixed-value domains' },
  { id: 'py-mixed-operators', profile: 'python.3.11', source: 'def combine(value):\n    values = [1, 2]\n    return values[0] + value\n', featureIds: ['dynamic-operators', 'collections', 'indexing'], requirement: 'Native overload dispatch, unknown operands and bounds/errors with visible effect ownership' },
  { id: 'js-keys-holes-spread', profile: 'javascript.es2022', source: 'function build(value) { const values = [value, , ...value, ]; const result = { value, "quoted-key": values[0], [value]: (-2) ** 2, ...value }; return result; }', featureIds: ['collections', 'indexing', 'dynamic-operators'], requirement: 'Shorthand, quoted and computed keys, array holes, spread and exponent precedence' },
  { id: 'py-containers-slices', profile: 'python.3.11', source: 'def build(value):\n    values = [0xff, *value]\n    pair = (values[0],)\n    items = {1, *value}\n    result = {"pair": pair, **value}\n    return values[1::2]\n', featureIds: ['scalar-values', 'collections', 'indexing'], requirement: 'Radix integers, list/set/dict spread, singleton tuples and explicit slice bounds' },
  { id: 'js-native-operators', profile: 'javascript.es2022', source: 'function combine(a, b) { const rest = a % b; const bits = a >>> b; return (a + b) ** rest == bits; }', featureIds: ['dynamic-operators'], requirement: 'Unknown native arithmetic, remainder, shifts and abstract comparison without numeric coercion' },
  { id: 'py-native-operators', profile: 'python.3.11', source: 'def combine(a, b):\n    rest = a // b\n    bits = a << b\n    return (a + b) ** rest == bits\n', featureIds: ['dynamic-operators'], requirement: 'Unknown Python floor division, shifts, overload dispatch and native comparison' },
  { id: 'js-exact-strings', profile: 'javascript.es2022', source: 'function strings() { return ["\\u0000", "quote\\\"", "\\u00e9"]; }', featureIds: ['scalar-values', 'collections'], requirement: 'Decoded strings survive controls, quotes and Unicode escapes' },
  { id: 'py-exact-strings', profile: 'python.3.11', source: 'def strings():\n    return ["\\u0000", "quote\\\"", r"\\n", "\\u00e9"]\n', featureIds: ['scalar-values', 'collections'], requirement: 'Decoded and raw Python strings preserve exact constant values' },
  { id: 'js-multiple-holes', profile: 'javascript.es2022', source: 'function build(value) { return [, , value, , , ]; }', featureIds: ['collections'], requirement: 'Every empty element owns its original comma and remains a hole after persistence' },
  { id: 'py-membership-identity', profile: 'python.3.11', source: 'def compare(a, b):\n    return [a is b, a is not b, a in b, a not in b]\n', featureIds: ['dynamic-operators', 'collections'], requirement: 'Native membership and identity remain distinct from rich equality' },
  { id: 'js-nested-effects', profile: 'javascript.es2022', source: 'function identity(value) { return value; } function build(value) { while (identity(value) == true) { break; } return { [identity(value)]: [identity(identity(value)), identity(value)] }; }', featureIds: ['collections', 'dynamic-operators'], requirement: 'Repeated condition effects, computed keys and nested calls retain exact ordered ownership' },
  { id: 'py-exact-radix-floats', profile: 'python.3.11', source: 'def values():\n    return [-0xff, 0b1_010, 1.0, 5e-324, +0.0, -9007199254740993, """line\nnext"""]\n', featureIds: ['scalar-values', 'numeric-domains', 'collections'], requirement: 'Signed radix arbitrary integers, subnormal/whole floats and multiline decoded strings' },
  { id: 'py-numeric-string-comparisons', profile: 'python.3.11', source: 'def compare():\n    value = 1.0 + 2.0\n    return [1.0 < 2.0, value == 3.0, "\\n" == "\\n"]\n', featureIds: ['scalar-values', 'numeric-domains', 'dynamic-operators', 'collections'], requirement: 'Native floats and decoded strings retain proven output pins and comparison domains' },
];
