import * as vscode from 'vscode';
import { strict as assert } from 'node:assert';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
export async function run(): Promise<void> {
  const root = vscode.workspace.workspaceFolders![0].uri;
  const second = vscode.workspace.workspaceFolders![1].uri;
  const extension = vscode.extensions.getExtension('vvs.vvs-vscode');
  assert.ok(extension, 'development extension loaded');
  await extension.activate();
  const manifest = JSON.parse(readFileSync(join(second.fsPath, '.vvs/project.json'), 'utf8'));
  const relative = Object.values(manifest.graphs.functions)[0] as string;
  const uri = vscode.Uri.joinPath(second, '.vvs', relative);
  const doc = await vscode.workspace.openTextDocument(uri);
  const graph = JSON.parse(doc.getText());
  const returning = graph.nodes.find((node: { data: { kindId: string } }) => node.data.kindId === 'flow_return');
  assert.ok(returning);
  returning.data.inlineValues.return_val = 9;
  const edit = new vscode.WorkspaceEdit();
  edit.replace(uri, new vscode.Range(doc.positionAt(0), doc.positionAt(doc.getText().length)), JSON.stringify(graph));
  assert.equal(await vscode.workspace.applyEdit(edit), true);
  assert.equal(doc.isDirty, true);
  // The initiating URI must win over whichever editor has focus in another root.
  await vscode.commands.executeCommand('vvs.generate', uri);
  const output = vscode.window.activeTextEditor!.document;
  assert.ok(output.uri.toString().startsWith(second.toString() + '/'));
  assert.ok(output.getText().includes('9'), 'dirty graph value generated');
  assert.equal(doc.isDirty, true, 'Generate does not save input buffers');
  const originalOutput = output.getText();
  const outputEdit = new vscode.WorkspaceEdit();
  outputEdit.insert(output.uri, new vscode.Position(0, 0), '// external dirty output\n');
  await vscode.workspace.applyEdit(outputEdit);
  await vscode.commands.executeCommand('vvs.generate', uri);
  assert.equal(new TextDecoder().decode(await vscode.workspace.fs.readFile(output.uri)), originalOutput, 'dirty output was protected');
  const malformed = new vscode.WorkspaceEdit();
  malformed.replace(uri, new vscode.Range(doc.positionAt(0), doc.positionAt(doc.getText().length)), '{');
  await vscode.workspace.applyEdit(malformed);
  await vscode.commands.executeCommand('vvs.generate', uri);
  assert.equal(new TextDecoder().decode(await vscode.workspace.fs.readFile(output.uri)), originalOutput, 'malformed dirty input did not fall back to disk');
  await vscode.commands.executeCommand('workbench.action.files.revert', output.uri);
  const restore = new vscode.WorkspaceEdit();
  restore.replace(uri, new vscode.Range(doc.positionAt(0), doc.positionAt(doc.getText().length)), JSON.stringify(graph));
  await vscode.workspace.applyEdit(restore);
  const external = '// externally edited on disk\n' + originalOutput;
  await vscode.workspace.fs.writeFile(output.uri, new TextEncoder().encode(external));
  await vscode.commands.executeCommand('vvs.generate', uri);
  assert.equal(new TextDecoder().decode(await vscode.workspace.fs.readFile(output.uri)), external, 'clean externally edited output was protected');
  assert.notEqual(root.toString(), second.toString());
  writeFileSync(process.env.VVS_SMOKE_RESULT!, JSON.stringify({ passed: true, checks: ['activation', 'multi-root identity', 'dirty input Generate', 'dirty output protection', 'malformed input guard', 'external output protection'] }));
}
