/** Analysis prerequisites; the branch graph planner remains separately gated. */
export const CSHARP_BRANCH_CASES = [
  { id: 'both-assign', body: 'int Value; if (Input > 0) { Value = Input; } else { Value = 0; } var observed = Value; return observed;', ok: true },
  { id: 'one-assign', body: 'int Value; if (Input > 0) { Value = Input; } var observed = Value; return observed;', ok: false },
  { id: 'else-cannot-read-then', body: 'int Value; if (Input > 0) { Value = Input; } else { Value++; } var observed = Value; return observed;', ok: false },
  { id: 'then-cannot-read-else', body: 'int Value; if (Input > 0) { Value = Value; } else { Value = Input; } var observed = Value; return observed;', ok: false },
  { id: 'return-path-excluded', body: 'int Value; if (Input > 0) { return Input; } else { Value = 0; } var observed = Value; return observed;', ok: true },
  { id: 'else-return-path-excluded', body: 'int Value; if (Input > 0) Value = Input; else return 0; var observed = Value; return observed;', ok: true },
  { id: 'both-return', body: 'if (Input > 0) return Input; else return 0;', ok: true },
  { id: 'return-not-all-paths', body: 'if (Input > 0) return Input;', ok: false },
  { id: 'constant-true-assign', body: 'int Value; if (true) Value = Input; var observed = Value; return observed;', ok: true },
  { id: 'constant-false-assign', body: 'int Value; if (false) Value = Input; var observed = Value; return observed;', ok: false },
  { id: 'constant-false-else', body: 'int Value; if (false) { Value++; } else { Value = Input; } var observed = Value; return observed;', ok: true },
  { id: 'constant-comparison', body: 'int Value; if (1U < 2L) Value = Input; var observed = Value; return observed;', ok: true },
  { id: 'no-mutable-constant-fold', body: 'int Value, Flag = 1; if (Flag == 1) Value = Input; var observed = Value; return observed;', ok: false },
  { id: 'nested-merge', body: 'int Value; if (Input > 0) { if (Input > 1) Value = Input; else Value = 1; } else { Value = 0; } var observed = Value; return observed;', ok: true },
  { id: 'nested-missing-path', body: 'int Value; if (Input > 0) { if (Input > 1) Value = Input; } else { Value = 0; } var observed = Value; return observed;', ok: false },
  { id: 'sibling-branch-locals', body: 'int Value; if (Input > 0) { int Same = Input; Value = Same; } else { int Same = 0; Value = Same; } var observed = Value; return observed;', ok: true },
  { id: 'branch-later-ancestor-reservation', body: 'if (Input > 0) { int Later = Input; } int Later = 0; var observed = Later; return observed;', ok: false },
  { id: 'branch-scope-escape', body: 'if (Input > 0) { int Inner = Input; } var observed = Inner; return observed;', ok: false, diagnostic: 'unsupported' },
  { id: 'invalid-integral-condition', body: 'if (Input) return 0; var observed = Input; return observed;', ok: false },
  { id: 'invalid-comparison-widths', parameters: 'long Input, ulong Other', body: 'if (Input < Other) return 0; var observed = Input; return observed;', ok: false },
  { id: 'short-circuit-dead-read', body: 'int Value; if (false && Value > 0) return 0; var observed = Input; return observed;', ok: true },
  { id: 'nonshort-circuit-read', body: 'int Value; if (false & (Value > 0)) return 0; var observed = Input; return observed;', ok: false },
  { id: 'logical-composed', body: 'int Value; if (!(Input < 0) && ((Input < 10) | false)) Value = Input; else Value = 0; var observed = Value; return observed;', ok: true },
  { id: 'constant-logical', body: 'int Value; if (!(1 > 2) && (true ^ false)) Value = Input; var observed = Value; return observed;', ok: true },
  { id: 'nested-checked-invalid', body: 'if (Input > 0) { checked { int Value = 2147483647 + 1; } } var observed = Input; return observed;', ok: false },
  { id: 'dead-type-error', body: 'if (false) { byte Value = 256; } var observed = Input; return observed;', ok: false },
  { id: 'dead-read-after-return', body: 'int Value; return Input; var observed = Value;', ok: true },
  { id: 'dead-name-before-declaration', body: 'return Input; var observed = Value; int Value = 0;', ok: false },
  { id: 'dead-read-new-binding', body: 'return Input; int Value; var observed = Value;', ok: true },
  { id: 'terminal-nested-block', body: '{ return Input; } int Value; var observed = Value;', ok: true },
  { id: 'both-return-dead-tail', body: 'int Value; if (Input > 0) return Input; else return 0; var observed = Value;', ok: true },
].map(spec => ({
  id: `source-branch-${spec.id}`,
  files: [{ path: 'Branches.cs', source: `class Branches { public static int Test(${spec.parameters ?? 'int Input'}) { ${spec.body} } }${spec.body.includes('var observed') ? '' : '\nclass NativeWitness { static void Check() { int observed = 0; } }'}` }],
  expected: { ok: spec.ok }, ...(spec.diagnostic ? { unresolvedInvalid: true } : { sourceBinding: 'checked' }),
}));
