import { expect, test } from 'bun:test';
import { normalizeProjectSnapshot, nativeScalarDeclarationGroup, transactNativeScalarDeclarationGroup } from '@vvs/graph-types';
import { previewNativeScalarSourceGraphs } from '@vvs/source-import';
import { configureNativeInventoryRuntime } from '../../../../packages/source-import/test/nativeInventoryRuntime';
import { normalizedNativeScalarSyntax } from '../../../../packages/source-import/src/nativeScalarSyntax';
import cases from '../../../../packages/source-import/test/native-local-source-cases.json';
import { emitProjectLikeCodePanel } from './emitProjectCode';
configureNativeInventoryRuntime();
for (const readonly of [false, true]) test(`C++ visible declaration group and Code-panel ownership readonly=${readonly}`, async () => {
  const source = readonly ? 'int grouped(int a) { const int first = a, second = first + 1; return second; }\n' : cases.cpp[1].source;
  const preview = await previewNativeScalarSourceGraphs(source, 'cpp', { fileName: 'grouped.cpp', entryPolicy: 'library', localStatements: true, groupedDeclarations: true });
  expect(preview.diagnostics).toEqual([]);
  const project = normalizeProjectSnapshot(JSON.parse(JSON.stringify(preview.snapshot)))!;
  const fn = project.functions[0], doc = project.documents[fn.id];
  const group = doc.nodes.find(node => node.data.kindId === 'native_declaration_group')!;
  const analysis = nativeScalarDeclarationGroup(doc, group.id, 'cpp', fn.id);
  expect(analysis.declarations.map(node => node.data.properties!.name)).toEqual(['first', 'second']);
  expect(analysis.mutable).toBe(!readonly);
  const output = emitProjectLikeCodePanel(project);
  expect(output.files[0].content).toBe(`int grouped(int a) {\n        ${readonly ? 'const ' : ''}int first = a, second = (first + 1);\n        return second;\n    }`);
  expect(normalizedNativeScalarSyntax(output.files[0].content, 'cpp')).toBe(normalizedNativeScalarSyntax(source, 'cpp'));
  for (const node of doc.nodes) if (node.data.kindId !== 'function_entry') expect(output.sourceMap[node.id]?.length).toBeGreaterThan(0);
  expect(emitProjectLikeCodePanel(normalizeProjectSnapshot(JSON.parse(JSON.stringify(project)))!).files).toEqual(output.files);
  const before = JSON.stringify(project);
  const boolean = { ...project, ...transactNativeScalarDeclarationGroup(project, group.id, { authoredType: 'bool' }) };
  expect(boolean.variables.every(variable => variable.typeRef?.kind === 'builtin' && variable.typeRef.id === 'data_boolean')).toBe(true);
  const loadedBoolean = normalizeProjectSnapshot(JSON.parse(JSON.stringify(boolean)))!;
  expect(() => emitProjectLikeCodePanel(loadedBoolean)).toThrow();
  const recovered = { ...loadedBoolean, ...transactNativeScalarDeclarationGroup(loadedBoolean, group.id, { authoredType: 'int' }) };
  expect(emitProjectLikeCodePanel(recovered).files).toEqual(output.files);
  expect(recovered.documents[fn.id].edges).toEqual(doc.edges);
  expect(JSON.stringify(project)).toBe(before);
  expect(source.slice((group.data.properties!.sourceOrigin as { start: number }).start, (group.data.properties!.sourceOrigin as { end: number }).end)).toContain('first = a, second = first + 1;');
  const first = analysis.declarations[0], second = analysis.declarations[1];
  const firstOrigin = first.data.properties!.sourceOrigin as { start: number; end: number };
  expect(source.slice(firstOrigin.start, firstOrigin.end)).toBe('first = a');
  const mutate = (change: (copy: typeof project) => void) => {
    const copy = structuredClone(project); change(copy); expect(() => emitProjectLikeCodePanel(copy)).toThrow();
  };
  mutate(copy => { copy.documents[fn.id].nodes.find(node => node.id === second.id)!.data.properties!.groupOwnerId = 'foreign'; });
  mutate(copy => { copy.documents[fn.id].nodes.find(node => node.id === group.id)!.data.properties!.nativeAuthoredType = 'bool'; });
  mutate(copy => { copy.documents[fn.id].nodes.find(node => node.id === group.id)!.data.properties!.nativeMutable = readonly; });
  mutate(copy => { copy.documents[fn.id].edges.find(edge => edge.source === group.id && edge.sourceHandle === 'declarations_exec')!.target = second.id; });
  mutate(copy => { copy.documents[fn.id].nodes.find(node => node.id === second.id)!.data.properties!.nativeAuthoredType = 'unsigned int'; });
  mutate(copy => { copy.documents[fn.id].edges.push({ ...copy.documents[fn.id].edges.find(edge => edge.source === group.id && edge.sourceHandle === 'exec_out')!, id: 'duplicate-group-exit' }); });
});
