import { expect, test } from 'bun:test';
import { createSourceImportWorkerService } from './sourceImportWorkerService';
import type { WorkerGraphReview, WorkerNativeScalarPreview } from './sourceImportWorkerProtocol';
import { configureNativeInventoryRuntime } from '../../../../packages/source-import/test/nativeInventoryRuntime';
import { nativeScalarSourceFixtures } from '../../../../packages/source-import/test/nativeScalarSourceFixtures';
import { nativeRuntimeSourceFixtures } from '../../../../packages/source-import/test/nativeRuntimeSourceFixtures';
import localCases from '../../../../packages/source-import/test/native-local-source-cases.json';
configureNativeInventoryRuntime();
test('C++ group worker preview and single-use receipt retain visible group ownership', async () => {
  const service = createSourceImportWorkerService();
  const config = { language: 'cpp' as const, source: localCases.cpp[1].source, fileName: 'grouped.cpp', mapStart: false, entryPolicy: 'library' as const };
  const preview = (await service({ ...config, id: 1, kind: 'preview' }) as { result: WorkerNativeScalarPreview }).result;
  expect(preview.regions[0].kind).toBe('candidate'); expect('snapshot' in preview).toBe(false);
  const reviewed = (await service({ ...config, id: 2, kind: 'review', regionIndex: 0 }) as { result: WorkerGraphReview }).result;
  expect(reviewed.diagnostics).toEqual([]);
  expect(Object.values(reviewed.snapshot!.documents).flatMap(doc => doc.nodes).filter(node => node.data.kindId === 'native_declaration_group')).toHaveLength(1);
  expect(await service({ ...config, id: 3, kind: 'accept', receipt: reviewed.receipt, snapshotJson: JSON.stringify(reviewed.snapshot) })).toMatchObject({ ok: true });
  expect(await service({ ...config, id: 4, kind: 'accept', receipt: reviewed.receipt, snapshotJson: JSON.stringify(reviewed.snapshot) })).toMatchObject({ ok: false, error: 'STALE_REVIEW' });
});
for (const language of ['cpp', 'rust', 'gdscript'] as const) test(`local worker receipt, owned preview and persistence ${language}`, async () => {
  const service = createSourceImportWorkerService();
  const config = { language, source: localCases[language][0].source, fileName: `locals.${{ cpp: 'cpp', rust: 'rs', gdscript: 'gd' }[language]}`, mapStart: false, entryPolicy: 'library' as const };
  const preview = (await service({ ...config, id: 1, kind: 'preview' }) as { result: WorkerNativeScalarPreview }).result;
  expect(preview.regions[0].kind).toBe('candidate'); expect('snapshot' in preview).toBe(false); expect('receipt' in preview).toBe(false);
  const reviewed = (await service({ ...config, id: 2, kind: 'review', regionIndex: 0 }) as { result: WorkerGraphReview }).result;
  expect(reviewed.diagnostics).toEqual([]); expect(reviewed.snapshot!.variables).toHaveLength(5);
  const tampered = structuredClone(reviewed.snapshot!); tampered.variables[0].name = 'foreign';
  expect(await service({ ...config, id: 3, kind: 'accept', receipt: reviewed.receipt, snapshotJson: JSON.stringify(tampered) })).toMatchObject({ ok: false, error: 'STALE_REVIEW' });
  expect(await service({ ...config, id: 4, kind: 'accept', receipt: reviewed.receipt, snapshotJson: JSON.stringify(reviewed.snapshot) })).toMatchObject({ ok: true });
  expect(await service({ ...config, id: 5, kind: 'accept', receipt: reviewed.receipt, snapshotJson: JSON.stringify(reviewed.snapshot) })).toMatchObject({ ok: false, error: 'STALE_REVIEW' });
});
for (const language of ['cpp', 'rust', 'gdscript'] as const) test(`runtime worker sealed module receipt ${language}`, async () => {
  const service = createSourceImportWorkerService();
  const config = { language, source: nativeRuntimeSourceFixtures[language], fileName: `runtime.${{ cpp: 'cpp', rust: 'rs', gdscript: 'gd' }[language]}`, mapStart: false, entryPolicy: 'library' as const };
  const preview = (await service({ ...config, id: 1, kind: 'preview' }) as { result: WorkerNativeScalarPreview }).result;
  expect(preview.regions[0].kind).toBe('candidate'); expect('snapshot' in preview).toBe(false);
  const reviewed = (await service({ ...config, id: 2, kind: 'review', regionIndex: 0 }) as { result: WorkerGraphReview }).result;
  expect(reviewed.diagnostics).toEqual([]);
  expect(await service({ ...config, id: 3, kind: 'accept', receipt: reviewed.receipt, snapshotJson: JSON.stringify(reviewed.snapshot) })).toMatchObject({ ok: true });
  expect(await service({ ...config, id: 4, kind: 'accept', receipt: reviewed.receipt, snapshotJson: JSON.stringify(reviewed.snapshot) })).toMatchObject({ ok: false, error: 'STALE_REVIEW' });
});
for (const language of ['cpp', 'rust', 'gdscript'] as const) test(`native worker preview, receipt and acceptance ${language}`, async () => {
  const service = createSourceImportWorkerService();
  const config = { language, source: nativeScalarSourceFixtures[language], fileName: `sample.${{ cpp: 'cpp', rust: 'rs', gdscript: 'gd' }[language]}`, mapStart: false, entryPolicy: 'library' as const };
  const preview = (await service({ ...config, id: 1, kind: 'preview' }) as { result: WorkerNativeScalarPreview }).result;
  expect(preview.regions[0].kind).toBe('candidate'); expect('snapshot' in preview).toBe(false); expect('receipt' in preview).toBe(false);
  const reviewed = await service({ ...config, id: 2, kind: 'review', regionIndex: 0 });
  expect(reviewed.ok).toBe(true);
  const review = (reviewed as { result: WorkerGraphReview }).result;
  expect(review.diagnostics).toEqual([]);
  expect(await service({ ...config, id: 3, kind: 'accept', receipt: review.receipt, snapshotJson: JSON.stringify(review.snapshot), language: 'javascript' })).toMatchObject({ ok: false, error: 'STALE_LANGUAGE' });
  expect(await service({ ...config, id: 4, kind: 'accept', receipt: review.receipt, snapshotJson: JSON.stringify(review.snapshot), source: config.source + ' ' })).toMatchObject({ ok: false });
  expect(await service({ ...config, id: 5, kind: 'accept', receipt: review.receipt, snapshotJson: JSON.stringify(review.snapshot) })).toMatchObject({ ok: true, result: { targetLanguage: language } });
  expect(await service({ ...config, id: 6, kind: 'accept', receipt: review.receipt, snapshotJson: JSON.stringify(review.snapshot) })).toMatchObject({ ok: false, error: 'STALE_REVIEW' });
  const old = service({ ...config, id: 7, kind: 'review', regionIndex: 0 });
  const recent = service({ id: 8, kind: 'preview', language: 'javascript', source: 'function sample(){ return 1; }' });
  expect(await old).toMatchObject({ ok: false, error: 'IMPORT_SUPERSEDED' });
  expect((await recent).ok).toBe(true);
});
