import { expect, test } from 'bun:test';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { transactNativeScalarLocal, normalizeProjectSnapshot } from '@vvs/graph-types';
import { previewNativeScalarSourceGraphs } from '@vvs/source-import';
import { configureNativeInventoryRuntime } from '../../../../packages/source-import/test/nativeInventoryRuntime';
import cases from '../../../../packages/source-import/test/native-local-source-cases.json';
import { emitProjectLikeCodePanel } from './emitProjectCode';
import { NativeLocalPanel } from '../components/layout/RightSidebar/NativeLocalPanel';
configureNativeInventoryRuntime();
for (const language of ['cpp', 'rust', 'gdscript'] as const) test(`native local coordinated inspector transaction ${language}`, async () => {
  const preview = await previewNativeScalarSourceGraphs(cases[language][0].source, language, { fileName: `locals.${{ cpp: 'cpp', rust: 'rs', gdscript: 'gd' }[language]}`, entryPolicy: 'library', localStatements: true });
  const original = normalizeProjectSnapshot(JSON.parse(JSON.stringify(preview.snapshot)))!;
  const fn = original.functions.find(fn => fn.name === 'accumulate')!;
  const declaration = original.documents[fn.id].nodes.find(node => node.data.kindId === 'var_define' && node.data.properties?.name === 'result')!;
  const variableId = String(declaration.data.properties!.symbolId);
  const before = JSON.stringify(original), edges = structuredClone(original.documents[fn.id].edges);
  const apply = (project: typeof original, edit: Parameters<typeof transactNativeScalarLocal>[2]) => ({ ...project, ...transactNativeScalarLocal(project, declaration.id, edit) });
  const renamed = apply(original, { name: 'editedResult' });
  expect(renamed.variables.find(variable => variable.id === variableId)!.name).toBe('editedResult');
  for (const node of renamed.documents[fn.id].nodes.filter(node => node.data.graphBinding?.symbolId === variableId)) expect(node.data.properties?.variableName).toBe('editedResult');
  expect(renamed.documents[fn.id].edges).toEqual(edges);
  expect(emitProjectLikeCodePanel(renamed).files[0].content).toContain('editedResult');
  expect(emitProjectLikeCodePanel(normalizeProjectSnapshot(JSON.parse(JSON.stringify(renamed)))!).files).toEqual(emitProjectLikeCodePanel(renamed).files);
  const readonly = apply(renamed, { mutable: false });
  expect(() => emitProjectLikeCodePanel(readonly)).toThrow();
  expect(readonly.documents[fn.id].edges).toEqual(edges);
  const recovered = apply(readonly, { mutable: true });
  expect(emitProjectLikeCodePanel(recovered).files).toEqual(emitProjectLikeCodePanel(renamed).files);
  const bool = apply(recovered, { authoredType: 'bool' });
  expect(bool.variables.find(variable => variable.id === variableId)!.type).toBe('data_boolean');
  expect(bool.variables.find(variable => variable.id === variableId)!.typeRef).toEqual({ kind: 'builtin', id: 'data_boolean' });
  const invalidReloaded = normalizeProjectSnapshot(JSON.parse(JSON.stringify(bool)))!;
  expect(invalidReloaded.variables.find(variable => variable.id === variableId)!.type).toBe('data_boolean');
  expect(() => emitProjectLikeCodePanel(invalidReloaded)).toThrow();
  expect(emitProjectLikeCodePanel(apply(invalidReloaded, { authoredType: String(declaration.data.properties!.nativeAuthoredType) })).files).toEqual(emitProjectLikeCodePanel(renamed).files);
  expect(bool.documents[fn.id].nodes.find(node => node.id === declaration.id)!.data.inputs.find(pin => pin.id === 'value')!.type).toBe('data_boolean');
  for (const node of bool.documents[fn.id].nodes.filter(node => node.data.kindId === 'variable_get' && node.data.graphBinding?.symbolId === variableId)) {
    expect(node.data.outputs[0].type).toBe('data_boolean');
    for (const edge of bool.documents[fn.id].edges.filter(edge => edge.source === node.id)) expect(edge.data?.pinType).toBe('data_boolean');
  }
  expect(bool.documents[fn.id].edges.map(edge => [edge.id, edge.source, edge.sourceHandle, edge.target, edge.targetHandle])).toEqual(edges.map(edge => [edge.id, edge.source, edge.sourceHandle, edge.target, edge.targetHandle]));
  expect(() => emitProjectLikeCodePanel(bool)).toThrow();
  expect(emitProjectLikeCodePanel(apply(bool, { authoredType: String(declaration.data.properties!.nativeAuthoredType) })).files).toEqual(emitProjectLikeCodePanel(renamed).files);
  expect(JSON.stringify(original)).toBe(before);
  expect(() => apply(original, { name: 'return' })).toThrow('EDIT');
  expect(() => apply(original, { authoredType: 'unknown' })).toThrow('TYPE');
  const foreign = structuredClone(original);
  foreign.variables.find(variable => variable.id === variableId)!.graphTabId = 'foreign';
  expect(() => apply(foreign, { name: 'editedResult' })).toThrow('INDEX_OWNER');
  const duplicate = structuredClone(original);
  duplicate.documents[fn.id].nodes.push({ ...structuredClone(declaration), id: 'other-declaration' });
  expect(() => apply(duplicate, { name: 'editedResult' })).toThrow('INDEX_OWNER');
  const unrelated = structuredClone(original);
  const otherFn = unrelated.functions.find(fn => fn.id !== original.functions[0].id)!;
  const otherEdge = unrelated.documents[otherFn.id].edges[0]; otherEdge.data = { ...otherEdge.data, pinType: 'data_boolean' };
  expect(apply(unrelated, { name: 'editedResult' }).documents[otherFn.id].edges[0]).toEqual(otherEdge);
  const markup = renderToStaticMarkup(createElement(NativeLocalPanel, { data: declaration.data, onChange: () => {} }));
  expect(markup).toContain('Native local name'); expect(markup).toContain('Native local type'); expect(markup).toContain('Mutable local');
  expect(markup).not.toMatch(/<details[^>]*\sopen/); expect(markup).not.toContain('Default value');
});
