import { expect, test } from 'bun:test';
import { transactNativeScalarSignature, editNativeScalarParameterType, editNativeScalarReturnType, analyzeProject } from '@vvs/graph-types';
import { previewNativeScalarSourceGraphs } from '@vvs/source-import';
import { configureNativeInventoryRuntime } from '../../../../packages/source-import/test/nativeInventoryRuntime';
import { nativeScalarSourceFixtures } from '../../../../packages/source-import/test/nativeScalarSourceFixtures';
import { emitProjectLikeCodePanel } from './emitProjectCode';
configureNativeInventoryRuntime();
for (const language of ['cpp', 'rust', 'gdscript'] as const) test(`coordinated native signature ports and invalid-edit recovery ${language}`, async () => {
  const preview = await previewNativeScalarSourceGraphs(nativeScalarSourceFixtures[language], language, { fileName: `sample.${{ cpp: 'cpp', rust: 'rs', gdscript: 'gd' }[language]}`, entryPolicy: 'library' });
  const original = preview.snapshot!, before = JSON.stringify(original);
  const definition = original.documents['main-graph'].nodes.find(node => node.data.properties?.functionName === 'Value')!;
  const parameterId = (definition.data.properties!.nativeParameters as { id: string }[])[0].id;
  const boolParameter = editNativeScalarParameterType(definition.data, parameterId, 'bool');
  const first = transactNativeScalarSignature(original, definition.id, boolParameter);
  const invalid = { ...original, ...first };
  expect(analyzeProject(invalid).ok).toBe(false);
  expect(() => emitProjectLikeCodePanel(invalid)).toThrow();
  const updatedDefinition = first.documents['main-graph'].nodes.find(node => node.id === definition.id)!;
  const second = transactNativeScalarSignature(first, definition.id, editNativeScalarReturnType(updatedDefinition.data, 'bool'));
  const changed = { ...original, ...second };
  expect(analyzeProject(changed).ok).toBe(true);
  const output = emitProjectLikeCodePanel(changed).files[0].content;
  expect(output).toContain(language === 'cpp' ? 'bool Value(const bool value)' : language === 'rust' ? 'fn Value(value: bool) -> bool' : 'func Value(value: bool) -> bool');
  expect(emitProjectLikeCodePanel(JSON.parse(JSON.stringify(changed))).files[0].content).toBe(output);
  const fn = second.functions.find(fn => fn.name === 'Value')!;
  expect(fn.overloads[0].parameters[0].type).toBe('data_boolean');
  expect(fn.overloads[0].returnType).toBe('data_boolean');
  expect(second.documents[fn.id].nodes.find(node => node.data.kindId === 'flow_return')!.data.inputs[1].type).toBe('data_boolean');
  expect(second.documents[fn.id].edges.find(edge => edge.targetHandle === 'val')!.data!.pinType).toBe('data_boolean');
  expect(JSON.stringify(original)).toBe(before);
  const corrupt = structuredClone(original);
  const other = corrupt.functions.find(fn => fn.name === 'value')!;
  const unrelated = corrupt.documents[other.id].edges.find(edge => edge.targetHandle === 'val')!;
  unrelated.data!.pinType = 'data_boolean';
  const retainedError = transactNativeScalarSignature(corrupt, definition.id, boolParameter);
  expect(retainedError.documents[other.id].edges.find(edge => edge.id === unrelated.id)!.data!.pinType).toBe('data_boolean');
  const foreign = structuredClone(definition.data); foreign.graphBinding!.symbolId = 'foreign';
  expect(() => transactNativeScalarSignature(original, definition.id, foreign)).toThrow('OWNER');
  const badSlot = structuredClone(definition.data); (badSlot.properties!.nativeParameters as { id: string }[])[0].id = 'other';
  expect(() => transactNativeScalarSignature(original, definition.id, badSlot)).toThrow('SIGNATURE');
  const missingOverload = structuredClone(original);
  const missingDefinition = missingOverload.documents['main-graph'].nodes.find(node => node.id === definition.id)!;
  missingDefinition.data.graphBinding!.overloadId = 'missing';
  expect(() => transactNativeScalarSignature(missingOverload, definition.id, missingDefinition.data)).toThrow('OWNER');
  const duplicate = structuredClone(original);
  duplicate.documents['main-graph'].nodes.push({ ...structuredClone(definition), id: 'duplicate-definition' });
  expect(() => transactNativeScalarSignature(duplicate, definition.id, boolParameter)).toThrow('OWNER');
});
